### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by joshafest** [HashEngineering/darkcoin-wallet#3]
unable to compile it say
error: package com.sun.xml.internal.ws.developer does not exist
if I removed this import then it say 
bitcoinj. core* does not exist

com.sun.XML.internal.WS.developer. is used for internals and not recommend to be used   ??

**Comment by HashEngineering** [comment]
Which branch are you compiling?
I haven working with release-0.13 and receive-ix without any compile issues with maven.

**Comment by joshafest** [comment]
it is darkcoin-wallet-release-4

**Comment by joshafest** [comment]
But darkcoinj build success by skipping tests by maven

**Comment by joshafest** [comment]
which branch have you compiled?
I used this and fails release-4

**Comment by lateminer** [comment]
I confirm this issue.

**Comment by HashEngineering** [comment]
Sorry about my previous comment, I thought this was about darkcoinj.

I don't know where this package is listed.  It doesn't show up in a search of all the files in the repo.

I currently use Android Studio 1.5 to compile this wallet.  I built this app 16 days ago to fix a bug and published it on Google Play.  I am not getting this error.

**Comment by HashEngineering** [comment]
Its possible that the problem is from Block.java in darkcoinj, where I mistakenly added this line with autocorrect:
//import com.sun.xml.internal.ws.api.config.management.policy.ManagedServiceAssertion;

https://github.com/HashEngineering/darkcoinj/blob/release-0.13/core/src/main/java/org/bitcoinj/core/Block.java#L43

Could you be using an out of date copy of darkcoinj?

**Comment by joshafest** [comment]
when I removed the import it says another error "bitcoinj:darkcoinj" not found.....also there is an error in Vegas coin and Vegas coinj  ...
the difficulty ... hash engineering.difficulty. Vegas gravity well doesn't exist.
Should I create pull request?

**Comment by HashEngineering** [comment]
We will need full error messages to solve these problems with bitcoinj:darkcoinj.  It is possible that my local system is setup correctly, but the repo on github has a missing file or a file that is not updated.

VegasCoin was a project where I was helping the main developer fix a few things.  The fix_difficulty branch had the working changes.  However, I have no interest in maintaining this repo.  A Pull request, if necessary, can be submitted to the original developer if his code is broken.  https://github.com/VegasCoin/vegascoinj

**Comment by lateminer** [comment]
Now I'm experiencing another error when compiling darkcoin-wallet.

In order to start compiling, I had to make a change in wallet/build.gradle file. I had to remove:

`tasks.withType(com.android.build.gradle.tasks.PackageApplication) {
    pkgTask ->
        pkgTask.jniFolders = new HashSet()
        pkgTask.jniFolders.add(new File(buildDir, 'native-libs'))
}`

And needed to add:

`...jniLibs.srcDirs = ['libs']
jniLibs.srcDir new File(buildDir, 'native-libs')`

But finally I got an error in CryptoTest. backups:

`java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at de.schildbach.wallet.util.CryptoTest.backups(CryptoTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Maybe there is a need to skip this test somehow?

**Comment by HashEngineering** [comment]
I don't currently run the tests when I compile, so I don't know about these
issues.  I will look into it as it would be better have working tests.

**Comment by HashEngineering** [comment]
That test that fails is using a bitcoin wallet file, which will fail to load with DASH.  Skip the tests.

**Comment by lateminer** [comment]
If I skip unit tests, it compiles fine.

**Comment by lateminer** [comment]
dd

**Comment by lateminer** [comment]
I have no idea what have happened, but when I tried to rebuild the wallet today it failed. I haven't touched anything, but now it can't find protobuf, spongycastle and other libraries: https://i.imgur.com/oes2BFe.png

This is the code, I had to add flatDir { dirs '../../darkcoinj/core/target' } to show the path to darkcoinj: https://github.com/lateminer/darkcoin-wallet/commit/e259510edb20442887479a7af6b18369bdd049a4

Then I tried to build original Bitcoin wallet, pointing it to my local bitcoinj folder: flatDir { dirs '../../bitcoinj/core/target' }. It failed too.

What am I doing wrong and WHY did it work yesterday?

**Comment by HashEngineering** [comment]
While I use Android Studio to build the app, I use maven to build darkcoinj using the command:
mvn clean install -DskipTests

Your error message is concerning the Sample-Integration-Android and not Wallet.  Your changes to build.gradle in wallet will have no effect.

**Comment by lateminer** [comment]
The same error goes in the wallet.

**Comment by schildbach** [comment]
It's apparently some dependency issue. @lateminer Can you try to build the upstream projects to see if they exhibit the same problem too? I think building under Windows isn't tested often.

**Comment by lateminer** [comment]
I have no idea what happened, but after several attemps of recompiling darkcoinj (bitcoinj) gradle began to catch it and the wallet compiles.

**Comment by HashEngineering** [comment]
On my Windows system, I was able to build bitcoinj (maven) and bitcoin-wallet (gradle) with no errors from the command line.

**Comment by lateminer** [comment]
I am able to build them now. Still wondering why I couldn't the day before.
